name: Continuous Integration

on: 
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '**/README.md'
      ## - '.github/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    ## Enable Caching
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    ## Configure JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'

    ## Build with maven
    - name: Perform build
      run: mvn verify

    ## Notify Mattermost
    - name: Notify Developers
      uses: 8398a7/action-slack@v3
      with:
        username: GitHub
        icon_emoji: octocat
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: ${{ github.actor != 'dependabot[bot]' }}


