name: Continuous Delivery

on: 
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  # checkout, build, deploy, notify mattermost
  build:
    uses: levigo/reusable-workflows/.github/workflows/continuous-delivery-np.yml@v3
    secrets: inherit
    with:
      mattermostChannel: 'neverpile-ci'
      jdkVersion: '11'

  # Update README.md
  updateReadme:
    needs: build
    uses: levigo/reusable-workflows/.github/workflows/update-readme-md.yml@v3
    secrets: inherit
    with:
      releaseVersion: ${{ needs.build.outputs.releaseVersion }}


