name: Continuous Integration

on: 
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  call-continuous-integration:
    uses: levigo/reusable-workflows/.github/workflows/continuous-integration.yml@feat/INF-28_license-check
    secrets: inherit
    with:
      mattermostChannel: 'neverpile-ci'
      matrix: '{"jdk": [11]}'
      sonarAnalysisEnabled: false

